### PR TITLE
add register and add missing fields

### PR DESCRIPTION
**Pull request by seekerlee**
add register and add missing fields.
My first time pull request. Please let me know if anything wrong.

### CODE REVIEW

**Comment by braydonf** [comment]
Looks like there is an issue with the build that's related to changes to upstream libstorj that's unrelated to changes in this PR.

**Comment by seekerlee** [comment]
@braydonf what should I do then? should I wait until the upstream libstorj release or should I just use the master branch of libstorj as dependency?

**Comment by braydonf** [comment]
I just went and updated it in https://github.com/Storj/node-libstorj/pull/59 so we should be good.

**Comment by braydonf** [comment]
Okay, I restarted the CI tests and it's building now. However it looks like the tests are not passing.

**Comment by braydonf** [comment]
There was a small issue with the test, and was updated in https://github.com/Storj/node-libstorj/pull/60

**Pull request merged**
